### ISSUE TITLE
ModuleNotFoundError with Python 3.12 using ExpertClient

### ISSUE THREAD

**Issue by deichbewohner** [discovertomorrow/futureEXPERT#1] opened 2024-04-18 09:00 UTC
**Environment:**
- Python Version: 3.12
- Library: futureexpert (installed from GitHub)

**Steps to Reproduce:**
1. Create a virtual environment with Python 3.12:
   ```
   python3.12 -m venv venv12
   source venv12/bin/activate
   ```
2. Install the `futureexpert` library from GitHub:
   ```
   pip install git+https://github.com/discovertomorrow/futureexpert
   ```
3. Attempt to import `ExpertClient`:
   ```
   python -c 'from futureexpert import ExpertClient'
   ```

**Expected Result:**
Successful import of the `ExpertClient` module.

**Actual Result:**
Encountered a `ModuleNotFoundError` related to `pkg_resources` during the import process. The traceback is as follows:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./venv12/lib/python3.12/site-packages/futureexpert/__init__.py", line 15, in <module>    from futureexpert.expert_client import ExpertClient
  File "./venv12/lib/python3.12/site-packages/futureexpert/expert_client.py", line 18, in <module>
    from futureexpert.future_api import FutureApiClient
  File "./venv12/lib/python3.12/site-packages/futureexpert/future_api.py", line 14, in <module>
    from keycloak import KeycloakOpenID
  File "./venv12/lib/python3.12/site-packages/keycloak/__init__.py", line 26, in <module>
    from ._version import __version__
  File "./venv12/lib/python3.12/site-packages/keycloak/_version.py", line 24, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Additional Information:**
The issue does not occur with Python 3.11.

Could you  assist in addressing this potential compatibility issue with Python 3.12?

**Comment by grthr** [comment] 2024-04-18 10:30
This is likely caused by a missing or broken setuptools installation and can most likely be easily fixed by running `pip install setuptools`.

More details can be found in this stackoverflow answer: https://stackoverflow.com/a/10538412/3572232

**Comment by grthr** [comment] 2024-07-12 11:42
We also updated the dependency which created the issue in the first place. There is no need to run `pip install setuptools` anymore.

**Comment by arnemu** [comment] 2024-07-12 12:45
I have tested the fix by reinstalling the `futureexpert` library from the updated GitHub repository, and I can confirm that the `ModuleNotFoundError` no longer occurs. The `ExpertClient` now imports successfully without any errors.

**Closed** 2024-07-12 12:46 UTC
